### PR TITLE
Adding a -recursive flag

### PR DESCRIPTION
**Pull request by es80**
I've had a go at adding a `-recursive` flag. This makes it a bit more user friendly compared to using `cshatag` via `find`. The bulk of the changes consist of three new functions in `main.go`.

There are a few things here that could be done differently. For example, if passed a directory but the `-recursive` flag is **_not_** set then `cshatag` could produce an error or it could process just the files in the directory. I went with the second of these options. 

Now that errors can occur before `checkFile` is called, I've slightly abused the `stats` struct to count them in order to produce a non-zero exit status.

I changed the possible exit status codes to better reflect the fact that multiple files can be processed at once. This assumes that if errors occur it would be preferable to continue processing as many files as possible. However, it might be considered better to exit immediately upon the first error. For example, prior to my changes this could happen from `getMtime` and `getActualAttr`.

### CODE REVIEW

**Comment by rfjakob** [comment]
Hi, thank you, code looks very good! A few comments:

1) I think we should error out with `3 File is not a regular file` unless `-recursive` is passed
2) The exit codes are effectively ABI. Changing them will break users' scripts. Please try to keep them compatible as much as possible. Add new codes if necessary but don't change the meaning of existing ones.
3) Add a test to https://github.com/rfjakob/cshatag/blob/master/tests/run_tests.sh ?

**Comment by es80** [comment]
Thanks!

I've made some changes to address the points you raised.
 
For the exit codes I've again used the `stats` struct to be able to differentiate the errors that might occur processing multiple files. It's perhaps only a temporary solution. A better approach would be to have every function return error values, wrapping them if necessary, and propagate them back to `main`. I've not quite got my head around exactly how that would work.

**Comment by es80** [comment]
Thanks, just to double check the behaviour is now as intended here is an example:

Create a directory containing two examples of non-regular files: a symbolic link and a named pipe
```
$ mkdir bar
$ touch foo
$ ln -s foo bar/link_to_foo
$ mkfifo bar/my_pipe
```

`cshatag` without the recursive flag treats non-regular files as errors
```
$ ./cshatag bar/*
Error: "bar/link_to_foo" is not a regular file.
Error: "bar/my_pipe" is not a regular file.
$ echo $?
3
```

but with the recursive flag they are just skipped with a message to stdout and exit code zero:
```
$ ./cshatag --recursive bar
<nonregular> bar/link_to_foo
<nonregular> bar/my_pipe
$ echo $?
0
```

in either case symbolic links are not followed so `foo` is still untagged:
```
$ getfattr -d foo
$
```

**Comment by rfjakob** [comment]
Yes, very good! Merged, thanks!

**Pull request merged**
