### PR TITLE
Makefile: use PREFIX for install

### PR DESCRIPTION
**Pull request by nicoulaj**
This allows to install to specified location:
```
make install PREFIX=/usr/local
```

I would like to create a package for your project, is it possible to create a tag ?

### CODE REVIEW

**Comment by bjornfor** [comment]
Hi @rfjakob. I'm also interested in packaging cshatag (for Nix/nixpkgs). Are you there? Please integrate this PR and add a git tag if you would like downstream users :-)

**Comment by rfjakob** [comment]
Whoops, i must have forgotten about this pr. Will do.

**Comment by nicoulaj** [comment]
@rfjakob bump :)

**Comment by rfjakob** [comment]
Slightly modified and commited to master: https://github.com/rfjakob/cshatag/commit/8d1225aabb7bdd3750f161133931b1c456bc2fdb

Thanks!

**Pull request closed without merging**
